// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFhrb9u4Ev0rBO8FbgvIj6T3hXxznXZroG28cbrAogkWtDiW2UikSo6cGoH/+2JIyXo6adHdb7FEzpyZ",
	"OTNzlEcemyw3GjQ6fvHIXbyFTPg/5ybLUyV0DPRLgoutylEZzS8a75gEFCp1bGNNxq7mq7dsBXFhFe7Z",
	"3Gi0JmVLazYqhTGPeG5NDhYVeBdxOEB//tPChl/wf0xqPJMSzKT2Vlrkh4iDtireZqBxhQIL1wcZnjOz",
	"YbgFFteQ66sstyYG5zjZKzJ+8Zmvirh88klnIs9B8ogvhUUlUv/wXpsHzSO+ulf+7V3E4ZvI8hTI5/E2",
	"7nN64NAqnRDgjRUZPBh7774/3rf1nUPErXL333/3mk4f6Bp8LZQFSdFVGW/BGUjm3TEAs/4CMZL7fhn6",
	"Ka9KX/phSm+MzQS9Zhtjm1UQzoFz5LPHC5HnqYrFWqUK930vb/ROWaPpqmPeqEb4ho49bMECw61yRwDe",
	"FPgYqyJ95ktrZBF7axHRJKES3UVcIWQeQK945QNhrdjT71igSE2ykH10n7T6WgBTEjSqjQLrAycKum52",
	"SisUw7EcTaT8arVcjV4PsSkWCImxA9mZl2+8VZGpdM9wK3AYwRpSoxPH0LT8zjyLqwYe8q9+LvI1KJ2U",
	"FPAd1on519lo+r/x9GzItYUMpPKcumz678JpvKyGgIXYZBloCZI1zDCHlrK2LwHX/Gkhu4bM7IBZY5AV",
	"DiwTIU1CS6boTDVScrBsMfvAcpOqOLCvE0WnLRWloOZUo7xPN+Lb1kw5OaOP5PJQS8cebKM/e124ecL4",
	"NSRFKrCkmdKycGj3zKHQUljpygLDTqSFQJCd5m+348fF6mb0/+l09J9X1I9X89H5j3VjI6KnE9EK/UjT",
	"cnkRQeqYuxG0Ic/mI+LmfP7f8dmPYO3UvTWEW1E8XffrchOcDlS5+8aEfbLOKexgYJaTD+bfkSETK1/H",
	"B4Vbpo0etYtZLs+5VahivyjfqWTLI/4BpCoyHvH35oFHfFHjEGl7dZYXnm6UgHUoOW+OK+wavhbgcIi0",
	"/gXLxT41InASgdqWuCsQrVoX2NQHvVz5jt4/t4SX4VQXfHn5OfQuN9qdEl2ALSmTAQopUDCl47SQxNhq",
	"xJJ4UTpxUYPUUZcY4yatgxisNV9DnnU28ukV2liM9faql1V/syg5MPNPjfifGMGDkrGh19rTrvnr5IBq",
	"j53uUGgItrLDAsUPRIuuDm6m/fvk3YC0O74aZJi1xnoKd1zLAaq9u7lZ0jAn/exPNFjy7+k04qGL+QVX",
	"Gl+d122rNEIClhxm4JxIBox7JKx6/VzHl+6r40OhLY9NeaJhYEfDPgZGYsvP+tCKDHSiNAT6DEpThsak",
	"7sQYeONvfxTZQJD0tFIdLWdBjOVgKYUg/YFyyXihYhnQjIwDk0XVYg19tJwNqaLg5LpI4cdEaQnOFin0",
	"lnYNpi3RJOj9iHpwRD34bAl72eqg7deULNDK6gcy0+xqvjhuH2QWEuW1R6eGjY88B3anSAYZy36BTFgR",
	"Phk0jm/10hpihyOz7JJM0RKgUqxyiNnunIGWuVH0rUEGpHKx2YH1+lVLJs2Dpm2idHKrj9aPMH6ffXjP",
	"XiSFkvQzqiS/i46T6SUTwTl9Y25EjC7yhsWtHg6nwuPhXOWgb447LDZpCjF6SYaQWM+p8S0RCBX62pUQ",
	"5yEBbFXmZrZc8IjvwLqQ5+n4bDwlXpkctMgVv+CvxtMxzb9c4NZ3wWR3Ngm4Qk8M7Vya9zk6JpgDpIa4",
	"h/3Q0nXsBYyTceR7D9niMqqYqUUGURj2i8uXlJpbbQELqx0TUqqgJRo5H1lIPX0bxtfCEZ+1z4ul89Jk",
	"QmmaCCoe3+obEv3HzCrnD/rvBDRsDSwWaQqSrYlnnaTPq6T/y7G4cEjjJfxbwdiQexodvhR+LS6Nw9/O",
	"wsYvZR84fG3kvlq6pDzqpUsXJ19c+MQJi+C5NdEXQ4d2U6ItwD8IYsOX83w6/VsAlHrGI+j8uyBs302R",
	"pvuS4a2ycX9jI4oU/zpkfg8OgPmk4VsOMREHyjMRd0WWCS9cQkTD1PWiuNGslQQjZUatJxKvDxq68o6M",
	"T3bnE37xWP71Rzka6iePRP3DZJ2atZs8SpWAw0PvdSa02oBDN3m0sAFLi65/ijBMUuVb9HA4/BkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
